version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  sca_scan:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Snyk
          command: npm install -g snyk
      - run:
          name: Authenticate Snyk
          command: snyk auth $SNYK_TOKEN
      - run:
          name: Run SCA Scan
          command: snyk test --severity-threshold=high
      - run:
          name: Monitor Snyk for vulnerabilities
          command: snyk monitor

  code_scan:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Snyk Code Analysis
          command: snyk code test

  container_scan:
    docker:
      - image: cimg/python:3.9  # Use a specific and verified version
    steps:
      - checkout
      - run:
          name: Install Snyk
          command: pip install snyk
      - run:
          name: Authenticate Snyk
          command: snyk auth $SNYK_TOKEN
      - run:
          name: Build Docker Image
          command: docker build -t goof .
      - run:
          name: Run Snyk Container Scan
          command: snyk container test goof --file=Dockerfile

workflows:
  version: 2
  scan_workflow:
    jobs:
      - install_dependencies
      - sca_scan:
          requires:
            - install_dependencies
      - code_scan:
          requires:
            - install_dependencies
      - container_scan
